### ISSUE TITLE
Assistance sending/receiving SDP message bodies

### ISSUE THREAD

**Issue by chriscao99** [martincyoung/SIPRig#2] opened 2018-07-17 16:38 UTC
I really need a tool that does exactly what SIPRig does, but is there any way to be able to specify different message bodies (SDP) and see the message bodies of the responses as well? I attached a screenshot of an example header/body I'm trying to send, and its response. If I were able to see the response message body as well, it would be very very helpful. Thanks so much!

<img width="655" alt="screen shot 2018-07-17 at 12 35 44 pm" src="https://user-images.githubusercontent.com/7874909/42832122-3e5b9418-89be-11e8-85b5-97c5b1336138.png">

**Comment by martincyoung** [comment] 2018-07-17 19:18
Hi Chris,

I'm not able to reproduce this.  

There's nothing special in the code that would leave off SDP in the response.  I suspect the reason you're not seeing anything is simply because sip.iptel.org is not sending you any SDP - notice how the Content-Length header in the response has value 0, suggesting there is no content attached.

Do you have a capture of this using wireshark (for example)?  That would show you for sure whether you're receiving any SDP from the far end.

Cheers,
Martin

**Comment by chriscao99** [comment] 2018-07-18 18:51
Hey Martin,

Thanks for getting back to this! I downloaded Wireshark and made a call to another computer using Linphone, then tried using SIPRig to mimic the SIP packets exchanged during that call. However, I ran into some issues again when specifying SDP bodies-- mainly I'm not seeing any SDP in the responses when there should be some. Here is a screenshot of me trying to mimic a SIP message to another computer. Any help would be appreciated-- thanks!

![screenshot 24](https://user-images.githubusercontent.com/7874909/42901192-e5fa18e0-8a98-11e8-85c1-1e6454cb6be6.png)

**Comment by martincyoung** [comment] 2018-07-18 21:13
Hi Chris,

I can't reach that address so I assume it's not reachable from the public internet.

Please can you attach the wireshark capture that corresponds to this response?  That will show me what your computer is receiving so we can narrow down where the problem is.

Thanks,
Martin

**Comment by martincyoung** [comment] 2018-08-03 07:56
Hi Chris,

As discussed, closing this as it was a false alarm.  Feel free to make your changes to enable multiple responses!

Martin

**Closed as completed by martincyoung** 2018-08-03 07:56 UTC
